### ISSUE TITLE
Default having http api on 0.0.0.0 should be localhost only, if anything.

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash-docker#10]

**Comment by jarpy** [comment]
As a security concern? Docker networking is making sure that TCP-9600 is not exposed unless the operator specifically asks for it, but Logstash is already set up for that to work should they do so. Note that we do not `EXPOSE 9600` in the Dockerfile.

I like this design, because it means an engineer who is using the image only has to make a decision/change in one place (at the Docker layer), without having to dig into the construction of the container image itself. It's all about having the image be as feature-complete as possible without requiring extensive reconfiguration from the user.
