### ISSUE TITLE
logstash-output-riemann not installed

### ISSUE THREAD

**Issue by ticktockhouse** [elastic/logstash-docker#25]
The `logstash-output-riemann` is not installed in the `logstash:5.2` docker image. Is there a reason for this? I need the output and if I want to use this version, it seems I need to use the Dockerfile to install it.

Is this by design?

**Comment by jarpy** [comment]
Hi.

Yes, this is by design. `logstash-output-riemann` is a community maintained plugin. There's a lot of them, and if we were to include one in the image, then we would have to include them all to be fair. It would also be impossible for us to test them all to the standard that we expect for the base image.

If you need community plugins, we suggest creating an extended image. In this case, that would simply be:

```dockerfile
FROM docker.elastic.co/logstash/logstash:5.3.0
RUN logstash-plugin install logstash-output-riemann
```
