### ISSUE TITLE
Add docker command line option to install plugins

### ISSUE THREAD

**Issue by monotek** [elastic/logstash-docker#43]
Currently we have to rebuild the docker image to get plugins installed.
Would be nice to have a docker command line option to install a plugin when starting the container.

**Comment by jarpy** [comment]
I feel like this is one of those things that is great when it works, but it could cause all sorts of problems in the face of network outages or other transient errors. Having your containers fail to start because `rubygems.org` is down is a pretty nasty operational story.

Somebody suggested something similar for the Elasticsearch image. Please [check out that issue](https://github.com/elastic/elasticsearch-docker/pull/26#issuecomment-278818245) if you're interested in our reasoning.

**Comment by okelet** [comment]
Quite old this thread, but just in case it helps:

```
docker run --name logstash -d docker.elastic.co/logstash/logstash:5.6.3 sh -c "logstash-plugin install logstash-output-gelf ; /usr/local/bin/docker-entrypoint"
```
