### ISSUE TITLE
Base image different

### ISSUE THREAD

**Issue by chandru9279** [elastic/logstash-docker#7]
Why is the base image different for the 3 tools?

ubuntu:16.04 - logstash-docker

docker.elastic.co/kibana/kibana-ubuntu-base:latest - kibana-docker

docker.elastic.co/elasticsearch/elasticsearch-alpine-base:latest - elasticsearch-docker

Unifying this as well will save space in host machines. Is this planned in the near future?

**Comment by jarpy** [comment]
A deeper question is "what is the ultimate base image for each product, and why are _they_ different?".

`kibana-ubuntu-base` and `elasticsearch-alpine-base` are themselves, not surprisingly, derived from different Alpine and Ubuntu images:

| Product image | Base image |
| :--- | :--- |
| `elasticsearch:5.0` | `alpine:latest`  |
| `kibana:5.0`  |  `phusion/baseimage:latest` |
| `logstash:5.0` | `ubuntu:16.04` |

Our ideal would be to have all products built on an Alpine base image to minimise the final image size that we are shipping. That's currently only feasible for Elasticsearch, however. Kibana and Logstash both have external dependencies that require a more traditional glibc- wow based distribution, rather than the musl libc used in Alpine Linux.

However, you are quite correct that there is no real need for Kibana and Logstash to have different ultimate base images because they are both Ubuntu-based. This is something of a case of historical accident. The Kibana image was built, verified and finalised before the Logstash image. When we started on Logstash, we realise that Ubuntu had done a good job of reducing their base image size with version 16.04, so we opted to base Logstash on that. We did not, at that time, migrate Kibana to `ubuntu:16.04` because of the solid base of testing we already had on `phusion/baseimage`. We didn't want to perturb the Kibana image and possibly compromise its stability. We probably will converge Kibana and Logstash onto the same base image when we can fully validate that choice, likely for the release of version 5.1.

As an aside, the reduction in total download size will probably not be that great, since by far the largest layer in the Logstash image comes from the installation of Java. Kibana doesn't use Java, so that layer is not shared. Effectively only the very base image layer is shared. In the case of `ubuntu:16.04`, that's about 50 MB.
