### ISSUE TITLE
Logstash tries to install template when elasticsearch is not ready

### ISSUE THREAD

**Issue by frederikbosch** [elastic/logstash-docker#85]
In my logstash pipeline a template is used. Logstash tries to install it, when ES is not ready yet. Giving the error Elasticsearch Unreachable. What are others users doing to prevent this? Add a bash script with sleep? `wait-for-it`? Isn't there a solution to retry to install the template when ES is available (which is bascially a few seconds later). I am on 5.6.9 by the way.

**Comment by jarpy** [comment]
> Isn't there a solution to retry to install the template when ES is available (which is bascially a few seconds later).

That would be my hope. It's probably a good question to ask on the [Logstash forum](https://discuss.elastic.co/c/logstash), because it's a potential problem regardless of which container orchestration system you're using or, indeed, whether you are using containers at all. It seems like people using Puppet, Ansible, or even good old Bash might have to handle the same thing.
