### ISSUE TITLE
Default configuration path is unaligned with rpm and deb installation methods

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash-docker#9]
Example:

`ADD pipeline/default.conf /usr/share/logstash/pipeline/logstash.conf`

In the rpm and deb, we put settings files in /etc/logstash/ and pipeline (`path.config`) in /etc/logstash/conf.d

I recommend we align on the way the rpm/deb do this.

**Comment by jarpy** [comment]
See #5 for a longer discussion, but here's my synopsis:

Right now, I'm using this directory structure to adhere to the [Logstash Directory Layout](https://www.elastic.co/guide/en/logstash/5.x/dir-layout.html) docs. Since we're building from the `.tar.gz` distribution (but see #14), we can put pipeline config anywhere without violating the docs. We can't, however, move the settings files the same way, since their location is specified for the `tar.gz` distribution (and in a different location to the deb/rpm versions). Thus, we can't fully satisfy the deb/rpm specification without violating the `.tar.gz` specification.

Maybe that doesn't matter, though. Maybe we just need a "Docker specification". I agree that having pipeline config in `/etc/logstash/conf.d` may be good for the "principle of least surprise" when people are coming from the deb/rpm world to the Docker image. So, I could see us making this change, but I'd want to be careful with both the Docker-specific documentation and the directory layout documentation to make sure we are not contradicting ourselves and really confusing our users.
